package com.miiikr.taixian.utils

object RequestInterface {

    val REQUEST_CODE_ID = 1
    val REQUEST_LOGIN_ID = 2
    val REQUEST_MAIN_ID = 3
    val REQUEST_MAIN_SEX = 4
    val REQUEST_TYPE_ID = 5
    val REQUEST_WATCH_BEAND_ID = 6
    val REQUEST_QR_ID = 7
    val REQUEST_USER_ID = 8
    val REQUEST_VIEW_ID = 9
    val REQUEST_UP_PIC_ID = 10
    val REQUEST_GET_USERINFO_ID = 11
    val REQUEST_UPDATE_NICNNAME_ID = 12
    val REQUEST_UPDATE_PHONE_ID = 13
    val REQUEST_COMPRESS_PIC_ID = 14
    val REQUEST_SUB_ID = 15
    val REQUEST_SELL_ID = 16
    val REQUEST_CHECK_ID = 17
    val REQUEST_EVA_ID = 18
    val REQUEST_CANCEL_EVA_ID = 19
    val REQUEST_CANCEL_SELL_ID = 20
    val REQUEST_SELL_WATCH_ID = 21
    val REQUEST_CHECK_DETAILS_ID = 22
    val REQUEST_EVA_DETAILS_ID = 23
    val REQUEST_Sell_DETAILS_ID = 24
    val REQUEST_Sell_CONFIRM_ID = 25
    val REQUEST_RECOVER_STORY_ID = 26
    val REQUEST_RECOVER_DELIVERY_ID = 27
    val REQUEST_RECOVER_GEM_ID = 28
    val REQUEST_LOGIN_WX_ID = 29


}